### ISSUE TITLE
[New Patient Registration] Estimate Age of patient 

### ISSUE THREAD

**Issue by Benilde** [esaude/esaude-emr-poc#105]
**[Actual Results]:** When the user clicks on any field, if the estimated displays NO it changes to YES without  changing the value of the date of bith

**[Expeted results]:** The system must change the estimated value only if the user uptade the value of the 
_**months, years, birthdate or days**_

**[Steps to reproduce]:** Go to the registration module, click on add a new patient_(+)_ button, on the fourth tab (Age)

![image](https://cloud.githubusercontent.com/assets/20538183/21604684/45dde454-d1ad-11e6-8e2a-8af932284311.png)

**Comment by ningosi** [comment]
The issue here  that need to be corrected is that, when a user select the birth date and end up clicking on the any of the age fields, and leaves without changing anything, the estimated field is changed. The required behavior is that when no changes are made to such fields, the estimated field should not change.
