### ISSUE TITLE
[New Patient Registration] The Drop Down of Fields of address should obey a descendant filter in the hierarchy

### ISSUE THREAD

**Issue by Benilde** [esaude/esaude-emr-poc#108]
**[Actual Results]**:When the user type the name of the district, location or administrative post the system automaticaly updates the information on the fields above. 
 

**[Expected results]:** When the user enters the name of a  district, location or administrative post the system must only display on the fields above the information related to the previouse field 

**[Steps to reproduce]** Go to the registration module, click on add a new patient_(+)_ button, on the first tab ( Address tab).

![image](https://cloud.githubusercontent.com/assets/20538183/21671791/74d7f77a-d326-11e6-866a-9d95eb976321.png)

**Comment by ningosi** [comment]
@larslemos seems this issue is realted to https://trello.com/c/OdpeD5hR. Are all those card items completed? and it it supposed to work in both POC and platform the same way. In RDE I can see it filtering from conutry>>province>>District>>Address2(**I dont't know what that represent is it suppossed to mean location?**). 

@Benilde in the POC am able to use the autocomplete feature to do that for the first four(4) entries and this is the results
![address](https://cloud.githubusercontent.com/assets/1763308/21883902/37a02a52-d8c2-11e6-812b-8f62bf2d8a69.png) is this suppossed to be done any different?

**Comment by ynurmahomed** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve Pending Issues/Bugs on POC](https://trello.com/c/n6P1sEan/215-resolve-pending-issues%2Fbugs-on-poc)

**Comment by ynurmahomed** [comment]
@Benilde Looks like this was fixed in e9de3984d7457f0c88f15b02d4ad599301954890.

**Comment by Benilde** [comment]
This is now working
